### PR TITLE
fix for backwards compatibility with ovirt 4.3

### LINKED ISSUE #136: Unable to get instance IP address with oVirt 4.3
Trying to ssh into existing guests fails with:
```
vagrant ssh
The VM has not reported an IP address. Please ensure the ovirt-guest-agent is running and the machine is up.
```
Even after ovirt shows the address provisioning new ones is stuck at:
`==> default: Waiting for VM to get an IP address...`

Regression caused by 8772ee9fa1e3827ec6547386f2619409a170593a and b8314fb4901ec7dd47d4b9f3e61f466ca04541ae

### PR DESCRIPTION
**Pull request by mika-b**
Fixes #136

I'm not fluent in ruby. This is the only ruby project I've ever worked on so there might be a better solution for this. Maybe this will do as a fallback for temporary backwards compatibility. At least it stands out and is easy to drop later.

### CODE REVIEW

File: lib/vagrant-ovirt4/action/read_ssh_info.rb [hunk 1]
```diff
@@ -37,6 +37,10 @@ def read_ssh_info(env)
           nics_service = server.nics_service
           nics = nics_service.list
           ip_addr = nics.collect { |nic_attachment| env[:connection].follow_link(nic_attachment.reported_devices).collect { |dev| dev.ips.collect { |ip| ip.address if ip.version == 'v4' } unless dev.ips.nil? } }.flatten.reject { |ip| ip.nil? }.first rescue nil
+          if ip_addr.nil?
```
Comment (myoung34) [inline lib/vagrant-ovirt4/action/read_ssh_info.rb:40]: it would be better here to use a begin rescue on line 39 then fall to this

perhaps remove the rescue nil from 39 and use this behavior? i can refactor after that change if you need

**Review by myoung34 — CHANGES_REQUESTED** [review]

File: lib/vagrant-ovirt4/action/read_ssh_info.rb (hunk 1 above)
Comment (mika-b) [reply lib/vagrant-ovirt4/action/read_ssh_info.rb]: In follow up commit, 4.4 handling moved to 'begin' and  4.3 to 'rescue'. That's how you meant it?

Comment (myoung34) [reply lib/vagrant-ovirt4/action/read_ssh_info.rb]: If this works as expected for you, then yes

@daFritz84 can you confirm this continues to work with your recent fix?

Comment (mika-b) [reply lib/vagrant-ovirt4/action/read_ssh_info.rb]: Yes, the fallback via rescue works with my 4.3 cluster.

Comment (myoung34) [reply lib/vagrant-ovirt4/action/read_ssh_info.rb]: If @dafritz84 with 4.4 can confirm this works Ill merge it

**Comment by GervaisdeM** [comment]
@myoung34 @daFritz84 I tested this against my 4.4.4 oVirt by checking out this pr and running vagrant up and the box came up fine.

**Comment by myoung34** [comment]
🎉
