### PR TITLE
fixed inconsistent usages of memory units (MB/MiB and GB/GiB)

### LINKED ISSUE #126: Memory size is not applied correctly
The memory options in the vagrantfile are not set up correctly. When I set all three memory sizes, e.g. to 4096MB (size, maximum, guaranteed), I expect that the virtual machines spins up with exactly that configuration. As for the example, it spins up with 3906MB, 15624MB, 3906MB. 

I know that there is some odd ovirt UI behaviour, where setting one memory size influences the other memory settings. It seems that this also happens at API level.  As for the web UI, I usually set the maximum memory first, then the memory size and finally the guaranteed memory.

@myoung34 Any thoughts what the intended behaviour for the plugin should be? Is this to be considered a bug?

Vagrantfile excerpt
```
  config.vm.provider :ovirt4 do |ovirt|
    ovirt.url = BLANKED
    ovirt.username = Secret.ovirt_username
    ovirt.password = Secret.ovirt_password
    ovirt.insecure = true
    ovirt.debug = false
    ovirt.cluster = 'Intel_Cluster'
    ovirt.template = 'centos-8-stream'
    ovirt.console = 'vnc'
    ovirt.memory_size = '4096MB'
    ovirt.memory_maximum = '4096MB'
    ovirt.memory_guaranteed = '4096MB'
    ovirt.cpu_cores = 2
    ovirt.cpu_threads = 2
    ovirt.cloud_init = <<EO_CLOUD_INIT
...
```

oVirt screenshot - edit dialogue
image

Log
```
❯ vagrant up
Bringing machine 'default' up with 'ovirt4' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          backup-monitoring
==> default:  -- Cluster:       Intel_Cluster
==> default:  -- Template:      centos-8-stream
==> default:  -- Console Type:  vnc
==> default:  -- BIOS Serial:
==> default:  -- Optimized For:
==> default:  -- Description:
==> default:  -- Comment:
==> default:  -- Memory:
==> default:  ---- Memory:      4096 MB
==> default:  ---- Maximum:     4096 MB
==> default:  ---- Guaranteed:  4096 MB
==> default:  -- Cpu:
==> default:  ---- Cores:       2
==> default:  ---- Sockets:     1
==> default:  ---- Threads:     2
==> default:  -- Cloud-Init:    true
==> default: Waiting for VM to become "ready" to start...
==> default: Starting VM.
==> default: Waiting for VM to get an IP address...
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Machine is booted and ready for use!
==> default: Rsyncing folder: /mnt/c/Users/SES/Source/ansible-backup-monitoring/vagrant/ => /vagrant
==> default: Setting hostname...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

### PR DESCRIPTION
**Pull request by daFritz84**
partly fixes #126 

Consolidated memory units to `MiB` and `GiB`. Now output from `vagrant` and `ovirt` should match up (i.e. 4096 MiB is shown as 4096MB at the web dashboard)

Tested OK with ovirt 4.4.2.6-1.el8 on Ubuntu 20.04 WSL on Windows 20H2

Log: 
```
❯ vagrant up
Bringing machine 'default' up with 'ovirt4' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          backup-monitoring
==> default:  -- Cluster:       Intel_Cluster
==> default:  -- Template:      centos-8-stream
==> default:  -- Console Type:  vnc
==> default:  -- BIOS Serial:
==> default:  -- Optimized For:
==> default:  -- Description:
==> default:  -- Comment:
==> default:  -- Memory:
==> default:  ---- Memory:      4096 MiB
==> default:  ---- Maximum:     4096 MiB
==> default:  ---- Guaranteed:  4096 MiB
==> default:  -- Cpu:
==> default:  ---- Cores:       2
==> default:  ---- Sockets:     1
==> default:  ---- Threads:     2
==> default:  -- Cloud-Init:    true
==> default: Waiting for VM to become "ready" to start...
==> default: Starting VM.
==> default: Waiting for VM to get an IP address...
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Got IP: 10.20.182.6
==> default: Machine is booted and ready for use!
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Rsyncing folder: /mnt/c/Users/SES/Source/ansible-backup-monitoring/vagrant/ => /vagrant
==> default: Setting hostname...
```

### CODE REVIEW

File: spec/vagrant-ovirt4/config_spec.rb [hunk 1]
```diff
@@ -68,13 +68,13 @@
...
+        instance.send("#{attribute}=".to_sym, "512 MiB")
         instance.finalize!
         instance.send(attribute).should == 512000000
       end
 
       it "should convert the value" do
-        instance.send("#{attribute}=".to_sym, "1 GB")
+        instance.send("#{attribute}=".to_sym, "1 GiB")
         instance.finalize!
         instance.send(attribute).should == 1000000000
```
Comment (daFritz84) [inline spec/vagrant-ovirt4/config_spec.rb:79]: I don't know if this constant needs updating, i.e. needs to be changed to 1073742000

File: spec/vagrant-ovirt4/config_spec.rb [hunk 2]
```diff
@@ -68,13 +68,13 @@
     [:memory_size, :memory_maximum, :memory_guaranteed].each do |attribute|
 
       it "should not default #{attribute} if overridden" do
-        instance.send("#{attribute}=".to_sym, "512 MB")
+        instance.send("#{attribute}=".to_sym, "512 MiB")
         instance.finalize!
         instance.send(attribute).should == 512000000
```
Comment (daFritz84) [inline spec/vagrant-ovirt4/config_spec.rb:73]: I don't know if this constant needs updating, i.e. needs to be changed to 536870900
